#!/usr/bin/with-contenv bash

redirect_cmd() {
	if [[ "${DEBUG}" == "true" ]]; then
		"$@"
	else
		"$@" >/dev/null 2>&1
	fi
}

echo "Starting Redis."
redirect_cmd exec s6-setuidgid abc \
	redis-server \
	/config/redis.conf
