#!/usr/bin/with-contenv bash

mkdir -p \
  /config/log \
  /var/run/redis/

[[ ! -f /config/redis.conf ]] &&
  cp /defaults/redis.conf /config/redis.conf

chown -R abc:abc \
  /config \
  /var/run/redis/
